# This file was generated by GoReleaser. DO NOT EDIT.
class Flares < Formula
  desc "Flares is a CloudFlare DNS backup tool"
  homepage "https://github.com/lfaoro/flares"
  url "https://github.com/lfaoro/flares/releases/download/v2.0.0-beta/flares_2.0.0-beta_darwin_amd64.tar.gz"
  version "2.0.0-beta"
  sha256 "ab45164df3add851cf1010b934bfbeadb42bee279ce2c538c074a6eb23200dff"

  def install
    bin.install "flares"
  end

  test do
    system "#{bin}/flares --version"
  end
end
