# This file was generated by GoReleaser. DO NOT EDIT.
class Gtag < Formula
  desc "gTag is a $(git tag) workflow tool for semantic versioning (semver.org)"
  homepage "https://github.com/lfaoro/gtag"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lfaoro/gtag/releases/download/0.1.1/gtag_0.1.1_darwin_amd64.tar.gz"
    sha256 "3af746ba8e96a796e02d525e4676f56c45a4729a6a34bf4c94dc4e2080d700aa"
  elsif OS.linux?
    url "https://github.com/lfaoro/gtag/releases/download/0.1.1/gtag_0.1.1_linux_amd64.tar.gz"
    sha256 "6d495ec2f93f84705f2af7be4268697c411c3c4134ff6a6533f32c7d17cdfdf6"
  end

  def install
    bin.install "gtag"
  end

  test do
    system "#{bin}/gtag --version"
  end
end
