# This file was generated by GoReleaser. DO NOT EDIT.
class Ion < Formula
  desc "a geeky & friendly way to simply encrypt locally & share."
  homepage "https://github.com/lfaoro/ion"
  url "https://github.com/lfaoro/ion/releases/download/v2.0.0/ion_2.0.0_darwin_amd64.tar.gz"
  version "2.0.0"
  sha256 "8460caf45a7117969f473b94f2cf0173d6814a1c36e25e0d314efcb068ec9521"

  def install
    bin.install "ion"
  end

  test do
    system "#{bin}/ncrypt --version"
  end
end
