# This file was generated by GoReleaser. DO NOT EDIT.
class Ion < Formula
  desc "a geeky & friendly way to simply encrypt locally & share."
  homepage "https://github.com/lfaoro/ion"
  url "https://github.com/lfaoro/ion/releases/download/v2.0.2/ion_2.0.2_darwin_amd64.tar.gz"
  version "2.0.2"
  sha256 "eb88180f5c3274a160e5d0bc9fe9defd9abc54560533cde6c955ff2266f84fef"

  def install
    bin.install "ion"
  end

  test do
    system "#{bin}/ncrypt --version"
  end
end
