# This file was generated by GoReleaser. DO NOT EDIT.
class Ion < Formula
  desc "a geeky & friendly way to simply encrypt locally & share."
  homepage "https://github.com/lfaoro/ion"
  url "https://github.com/lfaoro/ion/releases/download/v2.0.1/ion_2.0.1_darwin_amd64.tar.gz"
  version "2.0.1"
  sha256 "ae8cade8b52437815757f9288793c3b6b044be5b24c50ad5d56acfa7ff9a8013"

  def install
    bin.install "ion"
  end

  test do
    system "#{bin}/ncrypt --version"
  end
end
