# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssm < Formula
  desc "SSM | Secure Shell Manager"
  homepage "https://github.com/lfaoro/ssm"
  version "0.3.4"

  on_macos do
    url "https://github.com/lfaoro/ssm/releases/download/0.3.4/ssm_0.3.4_darwin_all.tar.gz"
    sha256 "6cd5c71b22e00b9b7b9980a2af89c212bcae651d3d29dbc69722246800a62c46"

    def install
      bin.install "ssm"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/lfaoro/ssm/releases/download/0.3.4/ssm_0.3.4_linux_x86_64.tar.gz"
      sha256 "3054a84784337b19c7bedcd80e5da1dad91495dae6741279b606330ea1a3384b"
      def install
        bin.install "ssm"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/lfaoro/ssm/releases/download/0.3.4/ssm_0.3.4_linux_armv6.tar.gz"
      sha256 "6775a939a7378f34d09be258dd9e3cfc9dcceebd295fc2dda17e9d2c7091bd32"
      def install
        bin.install "ssm"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/lfaoro/ssm/releases/download/0.3.4/ssm_0.3.4_linux_arm64.tar.gz"
      sha256 "f441c904d1e211dd8a96a644ad4c3b078e5b4bf7ea76e91b1c760b8a33a2ec05"
      def install
        bin.install "ssm"
      end
    end
  end
end
