# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swap < Formula
  desc "The Crypto Swap Terminal"
  homepage "https://github.com/lfaoro/swap"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lfaoro/swap/releases/download/v0.0.1/swap_darwin_x86_64"
      sha256 "756c15f6ec4abe5dea4ca758d820a713fce0f8a6a4ac978eca8025ba433dc66b"

      def install
        bin.install "swap_darwin_x86_64" => "swap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lfaoro/swap/releases/download/v0.0.1/swap_darwin_arm64"
      sha256 "d9c19282af5ed301c952380bf24a7c48b3d48d5091c8b44c0a635716d078ddb2"

      def install
        bin.install "swap_darwin_arm64" => "swap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/swap/releases/download/v0.0.1/swap_linux_x86_64"
        sha256 "20f3e842eade540ee7a181c28f3a08ed74c018f3c8a5b0b41aea53bdbe5c83d7"

        def install
          bin.install "swap_linux_x86_64" => "swap"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/swap/releases/download/v0.0.1/swap_linux_arm64"
        sha256 "65740b06f32682d23d6d2bbf8434bf5b9a6922a8d4fc6e5e3af569adb8e25f2b"

        def install
          bin.install "swap_linux_arm64" => "swap"
        end
      end
    end
  end
end
