# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swap < Formula
  desc "The Crypto Swap Terminal"
  homepage "https://github.com/lfaoro/swap"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lfaoro/swap/releases/download/v0.0.1/swap_darwin_x86_64"
      sha256 "274987ed23d3d2857eb6ecfcaccf57b2f80c1174d80d80a90bb61a7f4d2c5d2d"

      def install
        bin.install "swap_darwin_x86_64" => "swap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lfaoro/swap/releases/download/v0.0.1/swap_darwin_arm64"
      sha256 "dfdf78e43b3d7cc065b8712538e8a76380665f3837360fbc0949eb7790c330a7"

      def install
        bin.install "swap_darwin_arm64" => "swap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/swap/releases/download/v0.0.1/swap_linux_x86_64"
        sha256 "d1ad401bd4a6afc57974cc2a03f0d9825f48203c70aee73bd8d89b78f8a5e893"

        def install
          bin.install "swap_linux_x86_64" => "swap"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/swap/releases/download/v0.0.1/swap_linux_arm64"
        sha256 "af3bfec792beafc44cc973d7036de1d0cc758ac78b623cb98fad34d8edf8ae13"

        def install
          bin.install "swap_linux_arm64" => "swap"
        end
      end
    end
  end
end
