# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Troca < Formula
  desc "The Crypto Swap CLI"
  homepage "https://github.com/lfaoro/troca"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_darwin_x86_64"
      sha256 "fc8c119d62ec448ae20abed49082074ba13cad5414c88004d9eeb15296bf9f2d"

      def install
        bin.install "troca_darwin_x86_64" => "troca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_darwin_arm64"
      sha256 "f00a0c2d2c2d11835352aefb3b47809cfaf05cc9994420ee8af755c8995f283b"

      def install
        bin.install "troca_darwin_arm64" => "troca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_linux_x86_64"
        sha256 "77748e6436b4492e659caeef9b433aab074ef2b87bf6df77ef508190bce0cc09"

        def install
          bin.install "troca_linux_x86_64" => "troca"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_linux_arm64"
        sha256 "8dac23065a0e3f03bfc11b9fca105ced0e6a8e45539e4e10326500b668aaae65"

        def install
          bin.install "troca_linux_arm64" => "troca"
        end
      end
    end
  end
end
