# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Troca < Formula
  desc "The Crypto Swap CLI"
  homepage "https://github.com/lfaoro/troca"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_darwin_x86_64"
      sha256 "31041fd694e7854a0857e465d2c30d4c4b6c2b44474f863ab14e66aca928266c"

      def install
        bin.install "troca_darwin_x86_64" => "troca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_darwin_arm64"
      sha256 "de5ca07ab16b04b91a6cbe9202a1681a9aaacb0a0ed7dbb567258bbb226c35a0"

      def install
        bin.install "troca_darwin_arm64" => "troca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_linux_x86_64"
        sha256 "0dea390c56508f9580d3d194e4a9bcea50c3f2268757121892e1afca133993a2"

        def install
          bin.install "troca_linux_x86_64" => "troca"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_linux_arm64"
        sha256 "f8a3b7ccbb97c256a141f8bbb174c118cd169e682e5f4101e6a22641ebdc96d7"

        def install
          bin.install "troca_linux_arm64" => "troca"
        end
      end
    end
  end
end
