# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Troca < Formula
  desc "The Crypto Swap CLI"
  homepage "https://github.com/lfaoro/troca"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_darwin_x86_64"
      sha256 "787bf8a90756cdff72e6574a56c2bf7fefdaaa9f470281519d2bbe760df2921a"

      def install
        bin.install "troca_darwin_x86_64" => "troca"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_darwin_arm64"
      sha256 "1bd1d6c6b6763759fdf9e84f3f0e7f0ae450add1c2d6a7efe65ad619348f1f0e"

      def install
        bin.install "troca_darwin_arm64" => "troca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_linux_x86_64"
        sha256 "4d55060dd60fa50182da427502cc44e2d63b32b16736a6642540cf1a8a8f4f0a"

        def install
          bin.install "troca_linux_x86_64" => "troca"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/troca/releases/download/v0.0.1/troca_linux_arm64"
        sha256 "70a81d017974aede6834dc7325f04005c6b30eb6d13ac268893f8f4747e7cc99"

        def install
          bin.install "troca_linux_arm64" => "troca"
        end
      end
    end
  end
end
