# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tswap < Formula
  desc "The Crypto Swap Terminal"
  homepage "https://github.com/lfaoro/tswap"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lfaoro/tswap/releases/download/v0.0.1/tswap_darwin_x86_64"
      sha256 "d1f6943943a4092f4b13fa708bd7e9fbeb4e71c3834741df6359902314f4cb0e"

      def install
        bin.install "tswap_darwin_x86_64" => "tswap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lfaoro/tswap/releases/download/v0.0.1/tswap_darwin_arm64"
      sha256 "41cc6cdcfe1e9ad05ed65239acfc86f05c21ed6b0300a77df03ba87b22f2aeb4"

      def install
        bin.install "tswap_darwin_arm64" => "tswap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/tswap/releases/download/v0.0.1/tswap_linux_x86_64"
        sha256 "82a161bbbbbea35cf9b6f42e121627d0ccf33f9c7026a721885d794a76eb5e7b"

        def install
          bin.install "tswap_linux_x86_64" => "tswap"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/tswap/releases/download/v0.0.1/tswap_linux_arm64"
        sha256 "26d7cc6746f136806587853b53767dfba716ed39e31241f1f0f771632878d28b"

        def install
          bin.install "tswap_linux_arm64" => "tswap"
        end
      end
    end
  end
end
