# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tswap < Formula
  desc "The Crypto Swap Terminal"
  homepage "https://github.com/lfaoro/tswap"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lfaoro/tswap/releases/download/v0.0.1/tswap_darwin_x86_64"
      sha256 "76fd5e4de215e745e6acfa5907664bf9a43b2014f4e27c51a16340785ccd1558"

      def install
        bin.install "tswap_darwin_x86_64" => "tswap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lfaoro/tswap/releases/download/v0.0.1/tswap_darwin_arm64"
      sha256 "1ea20ae06adeec22563171d40c3b0deebcded93079e095640c5326c05ff3050a"

      def install
        bin.install "tswap_darwin_arm64" => "tswap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/tswap/releases/download/v0.0.1/tswap_linux_x86_64"
        sha256 "b252113892d7c41186706453a3599a1329a322b5a7e3bc7e96e6184a41afc528"

        def install
          bin.install "tswap_linux_x86_64" => "tswap"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lfaoro/tswap/releases/download/v0.0.1/tswap_linux_arm64"
        sha256 "dcc447695d0d6eafa7fde15d84dfeb9dcbb09e0b3b73890adeb00f8ef5d9e967"

        def install
          bin.install "tswap_linux_arm64" => "tswap"
        end
      end
    end
  end
end
