# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "16ly2xk7gcvp77w78bayaalxa59pl3nlm5xsj9rwlrrrf0gr9dfy";
    aarch64-linux = "1bi9byr86srgmmxsq9wc7cacw8a759gh60qppkhkdc6rpiydrw04";
    x86_64-darwin = "05a9zlisn800d3naxv0pzrnap10x8ydbnzf4w8gcvs8y82507d7g";
    aarch64-darwin = "11zzja89hnrdlsn7p33g5imi9kjchdlgkdfswrdf50idsp509vcq";
  };

  urlMap = {
    x86_64-linux = "https://github.com/lfaoro/flares/releases/download/v4.0.1/flares_4.0.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/lfaoro/flares/releases/download/v4.0.1/flares_4.0.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lfaoro/flares/releases/download/v4.0.1/flares_4.0.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/lfaoro/flares/releases/download/v4.0.1/flares_4.0.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "flares";
  version = "4.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./flares $out/bin/flares
  '';

  meta = {
    description = "Cloudflare DNS backup tool — export DNS records as BIND zone files";
    homepage = "https://github.com/lfaoro/flares";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
