# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1kbw4hpjqrn8jxgyl2axx2vcndif7yv2lk5i8vxjr3ym17r1qhvr";
    aarch64-linux = "07xgm7rpn3xcw36wpvslp8la7hyrlz9655y5dxxjmiyh0mvl95nk";
    x86_64-darwin = "1zm6xgjy7mchgjiczvfn06pg58f8grnnzzdqp072x8sikq93bdk5";
    aarch64-darwin = "0id7b4g6h8b6d8yrdhj2s42v0187klfchqirmqjnlqs7jizjw4g2";
  };

  urlMap = {
    x86_64-linux = "https://github.com/lfaoro/flares/releases/download/v4.0.1/flares_4.0.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/lfaoro/flares/releases/download/v4.0.1/flares_4.0.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lfaoro/flares/releases/download/v4.0.1/flares_4.0.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/lfaoro/flares/releases/download/v4.0.1/flares_4.0.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "flares";
  version = "4.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./flares $out/bin/flares
  '';

  meta = {
    description = "Cloudflare DNS backup tool — export DNS records as BIND zone files";
    homepage = "https://github.com/lfaoro/flares";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
