# This file was generated by GoReleaser. DO NOT EDIT.
cask "flares" do
  version "4.0.1"

  on_macos do
    on_intel do
      sha256 "efb4038a401ee9cd1ee2c47dbb9a471d84ab6cfe17ecaeec680020ab23fd4915"
      url "https://github.com/lfaoro/flares/releases/download/v#{version}/flares_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "98ed04cad52d82e25ae6dab5f968834cce146b2c6f8c7baca62d5b989092ff87"
      url "https://github.com/lfaoro/flares/releases/download/v#{version}/flares_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "deb5941f703967ca7392ba974aeda03715d5a9525e2d74f83977b37766179e9a"
      url "https://github.com/lfaoro/flares/releases/download/v#{version}/flares_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "04f0dc7cbcd9b036e1bc1703035f2a4721ce143b8c27ac7bad2f6b83b25f29ae"
      url "https://github.com/lfaoro/flares/releases/download/v#{version}/flares_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flares"
  desc "Cloudflare DNS backup tool — export DNS records as BIND zone files"
  homepage "https://github.com/lfaoro/flares"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flares"

  # No zap stanza required

end
