# This file was generated by GoReleaser. DO NOT EDIT.
cask "flares" do
  version "4.0.1"

  on_macos do
    on_intel do
      sha256 "65b635129e51a32e0eb8b8fd6f6d7ec8a1f2ae01d6edcfa27c90d5e3e5eba6fe"
      url "https://github.com/lfaoro/flares/releases/download/v#{version}/flares_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2112e7f9447636a25ae3962c81c9d0705b005d142c2963d6a6621681e59a745"
      url "https://github.com/lfaoro/flares/releases/download/v#{version}/flares_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "79431cf209d58f2cfb46b14c2ab63f2e36cbb6e85d09ea5f97c8662c2f247ccd"
      url "https://github.com/lfaoro/flares/releases/download/v#{version}/flares_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d396447705d0c72a7b6fc59762d2a7d9c3a328ba54efcbcde0ac0f7bf3a9af1f"
      url "https://github.com/lfaoro/flares/releases/download/v#{version}/flares_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flares"
  desc "Cloudflare DNS backup tool — export DNS records as BIND zone files"
  homepage "https://github.com/lfaoro/flares"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flares"

  # No zap stanza required

end
