# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssm" do
  version "2.5.1"

  on_macos do
    sha256 "917f124ccdc3a7defd2a4a6b0819567f3694a2520c295ba8a422695af1b832f2"
    url "https://github.com/lfaoro/ssm/releases/download/#{version}/ssm_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "9ae5f40696d7c03f731fdcd1f2ee5bb4b2ec91b01dbb443e0ec49cf4e7c83908"
      url "https://github.com/lfaoro/ssm/releases/download/#{version}/ssm_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fa7cf9fec80ff14ffd9ea3c7d8d8a4c8e22a2c2e44f17ccb7a64710d31cf8ca1"
      url "https://github.com/lfaoro/ssm/releases/download/#{version}/ssm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssm"
  desc "SSM | Secure Shell Manager"
  homepage "https://github.com/lfaoro/ssm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssm"

  # No zap stanza required

end
