# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssm" do
  version "2.5.2"

  on_macos do
    sha256 "499179ab052d2a4cfb8f1a4d4632ff893dc8afb1763bfc6fd0228cdf4703feea"
    url "https://github.com/lfaoro/ssm/releases/download/#{version}/ssm_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "681370df261f59566ce12e3a10f52506935525bec59bafb1bcb04649f7c54cd3"
      url "https://github.com/lfaoro/ssm/releases/download/#{version}/ssm_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8ac81b18fcc5e575da721dfae3f8cff4f4db0aca7fbfdb1b7df27ea0289e0c3a"
      url "https://github.com/lfaoro/ssm/releases/download/#{version}/ssm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssm"
  desc "SSM | Secure Shell Manager"
  homepage "https://github.com/lfaoro/ssm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssm"

  # No zap stanza required

end
