# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssm" do
  version "2.6.0"

  on_macos do
    sha256 "5bbca0f954c26ae386b436ce72780f6484fc86158e24e09c02fdc8a4a00bba02"
    url "https://github.com/lfaoro/ssm/releases/download/#{version}/ssm_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "09add1a6a1fcd68d1a04c7e4f2435411b17a44f39ed83707960353518a336dbc"
      url "https://github.com/lfaoro/ssm/releases/download/#{version}/ssm_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1e8b533784756be380070421fa2a4986ce648390cdbf123e4ad6eae00eda84e4"
      url "https://github.com/lfaoro/ssm/releases/download/#{version}/ssm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ssm"
  desc "SSM | Secure Shell Manager"
  homepage "https://github.com/lfaoro/ssm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssm"

  # No zap stanza required

end
