# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  makeWrapper,
  ssh,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0k8hn1ywcp9bd4gy1qcxdzdmdwzv5m68v090ss32pvd8andmdzl2";
    aarch64-linux = "1w6rrzzfqq9nr5gkyg4hr05grg3j1yzmgwl9yfb5v8a9p6qjia0r";
    x86_64-darwin = "0ql1l36743k25f6b56khbzz9flmq8l34gjxi8mqgssrn008kpgw4";
    aarch64-darwin = "0ql1l36743k25f6b56khbzz9flmq8l34gjxi8mqgssrn008kpgw4";
  };

  urlMap = {
    x86_64-linux = "https://github.com/lfaoro/ssm/releases/download/1.0.1/ssm_1.0.1_linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/lfaoro/ssm/releases/download/1.0.1/ssm_1.0.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lfaoro/ssm/releases/download/1.0.1/ssm_1.0.1_darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/lfaoro/ssm/releases/download/1.0.1/ssm_1.0.1_darwin_all.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "ssm";
  version = "1.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./ssm $out/bin/ssm
    wrapProgram $out/bin/ssm --prefix PATH : ${lib.makeBinPath ([ ssh ])}
  '';

  meta = {
    description = "SSM | Secure Shell Manager";
    homepage = "https://github.com/lfaoro/ssm";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
