# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  makeWrapper,
  ssh,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "0635jqk523c7haf7isdi7wa5xl19fk9k24dp86qr3lc3jaa8i8cg";
    x86_64-linux = "1mvfzcc15226apbkrrbcwbinkz0a618hkpdl62668cihksj0c3x1";
    armv6l-linux = "19nn91xbiz338ja6mn50vj8w0aa0a8zxs0p29j2r5i58ahcrq917";
    aarch64-linux = "1f0am3v3d6s3ys4yyflki7nmxarzqm6720gjhb7pqfnhyadhbk03";
    x86_64-darwin = "0gbc6xni129l1jzkln6lhs347vnigqq3wzx6vfd9wjaja0y4kxf3";
    aarch64-darwin = "0gbc6xni129l1jzkln6lhs347vnigqq3wzx6vfd9wjaja0y4kxf3";
  };

  urlMap = {
    i686-linux = "https://github.com/lfaoro/ssm/releases/download/0.4.2/ssm_0.4.2_linux_i386.tar.gz";
    x86_64-linux = "https://github.com/lfaoro/ssm/releases/download/0.4.2/ssm_0.4.2_linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/lfaoro/ssm/releases/download/0.4.2/ssm_0.4.2_linux_armv6.tar.gz";
    aarch64-linux = "https://github.com/lfaoro/ssm/releases/download/0.4.2/ssm_0.4.2_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lfaoro/ssm/releases/download/0.4.2/ssm_0.4.2_darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/lfaoro/ssm/releases/download/0.4.2/ssm_0.4.2_darwin_all.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "ssm";
  version = "0.4.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./ssm $out/bin/ssm
    wrapProgram $out/bin/ssm --prefix PATH : ${lib.makeBinPath ([ ssh ])}
  '';

  meta = {
    description = "SSM | Secure Shell Manager";
    homepage = "https://github.com/lfaoro/ssm";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
