# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  makeWrapper,
  ssh,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1pwjxvgvnk7xnih0k08bf90bdhc2sscqjakpn8hsv6d7nc7nhgrf";
    x86_64-linux = "1c0i08a2gch2kclmzlh0wb3ksd6px8zwwmp3s5xg6hg1177vvcn0";
    armv6l-linux = "1nf2lhkgqqvc7a1cgadyxrhjlc8hkjc4yfapd2ijim1dlwgxzmjm";
    aarch64-linux = "11sg0dm12z7pa1a141f41p8y3kzr6hh7j45g76yfzwzcr93268f1";
    x86_64-darwin = "0g6fia84y13a8fg8lnv5q99fwg7mmkd502sf3fflhg6g5083y6gr";
    aarch64-darwin = "0g6fia84y13a8fg8lnv5q99fwg7mmkd502sf3fflhg6g5083y6gr";
  };

  urlMap = {
    i686-linux = "https://github.com/lfaoro/ssm/releases/download/1.0.0/ssm_1.0.0_linux_i386.tar.gz";
    x86_64-linux = "https://github.com/lfaoro/ssm/releases/download/1.0.0/ssm_1.0.0_linux_x86_64.tar.gz";
    armv6l-linux = "https://github.com/lfaoro/ssm/releases/download/1.0.0/ssm_1.0.0_linux_armv6.tar.gz";
    aarch64-linux = "https://github.com/lfaoro/ssm/releases/download/1.0.0/ssm_1.0.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lfaoro/ssm/releases/download/1.0.0/ssm_1.0.0_darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/lfaoro/ssm/releases/download/1.0.0/ssm_1.0.0_darwin_all.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "ssm";
  version = "1.0.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./ssm $out/bin/ssm
    wrapProgram $out/bin/ssm --prefix PATH : ${lib.makeBinPath ([ ssh ])}
  '';

  meta = {
    description = "SSM | Secure Shell Manager";
    homepage = "https://github.com/lfaoro/ssm";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
